<?php

use Illuminate\Database\Seeder;

class ProblemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $problems = [
            [
                'title' => 'Multiples of 3 and 5',
                'level' => 'low',
                'answer' => 233168,
                'score' => 5,
                'description' => 'If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.',
            ] ,
            [
                'title' => 'Fibonacci Numbers',
                'level' => 'low',
                'answer' => 4613732,
                'score' => 5,
                'description' => 'Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
`1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...`
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
',
            ],
            [
                'title' => 'Largest prime factor',
                'level' => 'low',
                'answer' => 6857,
                'score' => 10,
                'description' => 'The prime factors of *13195* are `5, 7, 13 and 29`.
What is the largest prime factor of the number `600851475143` ?
',
            ],
            [
                'title' => 'Largest palindrome product',
                'level' => 'low',
                'answer' => 906609,
                'score' => 5,
                'description' => 'A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.
',
            ],
            [
                'title' => 'Smallest Multiple',
                'level' => 'low',
                'answer' => 232792560,
                'score' => 15,
                'description' => '2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
',
            ],
            [
                'title' => '10001st prime number',
                'level' => 'low',
                'answer' => 104743,
                'score' => 15,
                'description' => 'By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
What is the 10.001st prime number?',
            ],
            [
                'title' => 'Sum of all primes below',
                'level' => 'low',
                'answer' => 142913828922,
                'score' => 15,
                'description' => 'The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
Find the sum of all the primes below two million.',
            ]
            ,
            [
                'title' => 'Lexicographic permutations',
                'level' => 'low',
                'answer' => 2783915460,
                'score' => 15,
                'description' => 'A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:
012   021   102   120   201   210
What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?
',
            ],
            [
                'title' => 'Pandigital products',
                'level' => 'low',
                'answer' => 45228,
                'score' => 20,
                'description' => 'We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once; for example, the 5-digit number, 15234, is 1 through 5 pandigital.
The product 7254 is unusual, as the identity, 39 × 186 = 7254, containing multiplicand, multiplier, and product is 1 through 9 pandigital.
Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital.
HINT: Some products can be obtained in more than one way so be sure to only include it once in your sum.
',
            ],
            [
                'title' => 'Curious number',
                'level' => 'low',
                'answer' => 40730,
                'score' => 20,
                'description' => '145 is a curious number, as 1! + 4! + 5! = 1 + 24 + 120 = 145.
Find the sum of all numbers which are equal to the sum of the factorial of their digits.
Note: as 1! = 1 and 2! = 2 are not sums they are not included.
',
            ],
            [
                'title' => 'Circular Primes',
                'level' => 'low',
                'answer' => 55,
                'score' => 10,
                'description' => 'The number, 197, is called a circular prime because all rotations of the digits: 197, 971, and 719, are themselves prime.
There are thirteen such primes below 100: 2, 3, 5, 7, 11, 13, 17, 31, 37, 71, 73, 79, and 97.
How many circular primes are there below one million?
',
            ],
            [
                'title' => 'Double-base Palindrome',
                'level' => 'low',
                'answer' => 872187,
                'score' => 10,
                'description' => 'The decimal number, 585 = 10010010012 (binary), is palindromic in both bases.
Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2.
(Please note that the palindromic number, in either base, may not include leading zeros.)
',
            ],
            [
                'title' => 'Eleven truncatable primes',
                'level' => 'low',
                'answer' => 748317,
                'score' => 15,
                'description' => 'The number 3797 has an interesting property. Being prime itself, it is possible to continuously remove digits from left to right, and remain prime at each stage: 3797, 797, 97, and 7. Similarly we can work from right to left: 3797, 379, 37, and 3.
Find the sum of the only eleven primes that are both truncatable from left to right and right to left.
NOTE: 2, 3, 5, and 7 are not considered to be truncatable primes.
',
            ],
            [
                'title' => 'Integer right triangles',
                'level' => 'low',
                'answer' => 840,
                'score' => 10,
                'description' => 'If p is the perimeter of a right angle triangle with integral length sides, {a,b,c}, there are exactly three solutions for p = 120.
{20,48,52}, {24,45,51}, {30,40,50}
For which value of p ≤ 1000, is the number of solutions maximised?
',
            ],
            [
                'title' => 'Find the largest pandigital prime',
                'level' => 'low',
                'answer' => 7652413,
                'score' => 5,
                'description' => 'We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once. For example, 2143 is a 4-digit pandigital and is also prime.
What is the largest n-digit pandigital prime that exists?
',
            ],
            [
                'title' => 'Permuted multiples',
                'level' => 'low',
                'answer' => 142857,
                'score' => 10,
                'description' => 'It can be seen that the number, 125874, and its double, 251748, contain exactly the same digits, but in a different order.
Find the smallest positive integer, x, such that 2x, 3x, 4x, 5x, and 6x, contain the same digits.
',
            ],
            [
                'title' => 'Positive divisors',
                'level' => 'low',
                'answer' => 986262,
                'score' => 5,
                'description' => 'Find the number of integers 1 < n < 107, for which n and n + 1 have the same number of positive divisors. For example, 14 has the positive divisors 1, 2, 7, 14 while 15 has 1, 3, 5, 15.',
            ],
            [
                'title' => 'Prime generating integers',
                'level' => 'low',
                'answer' => 1739023853137,
                'score' => 10,
                'description' => 'Consider the divisors of 30: 1,2,3,5,6,10,15,30.
It can be seen that for every divisor d of 30, d+30/d is prime.
Find the sum of all positive integers n not exceeding 100 000 000
such that for every divisor d of n, d+n/d is prime.
',
            ],
            [
                'title' => 'Under the Rainbow',
                'level' => 'low',
                'answer' => 6.818741802,
                'score' => 10,
                'description' => '70 colored balls are placed in an urn, 10 for each of the seven rainbow colors.
What is the expected number of distinct colors in 20 randomly picked balls?
Give your answer with nine digits after the decimal point (a.bcdefghij).
',
            ],
            [
                'title' => 'Factorial digit sum ',
                'level' => 'medium',
                'answer' => 648,
                'score' => 25,
                'description' => 'n! means n × (n − 1) × ... × 3 × 2 × 1
For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
Find the sum of the digits in the number 100!
',
            ],
            [
                'title' => 'Prime pair sets',
                'level' => 'medium',
                'answer' => 26033,
                'score' => 20,
                'description' => 'The primes 3, 7, 109, and 673, are quite remarkable. By taking any two primes and concatenating them in any order the result will always be prime. For example, taking 7 and 109, both 7109 and 1097 are prime. The sum of these four primes, 792, represents the lowest sum for a set of four primes with this property.
Find the lowest sum for a set of five primes for which any two primes concatenate to produce another prime.
',
            ],
            [
                'title' => 'The Sum of primes',
                'level' => 'medium',
                'answer' => 71,
                'score' => 20,
                'description' => 'It is possible to write ten as the sum of primes in exactly five different ways:
 - 7 + 3
 - 5 + 5
 - 5 + 3 + 2
 - 3 + 3 + 2 + 2
 - 2 + 2 + 2 + 2 + 2
What is the first value which can be written as the sum of primes in over five thousand different ways?
',
            ],
            [
                'title' => 'Square root digital expansion',
                'level' => 'medium',
                'answer' => 40886,
                'score' => 20,
                'description' => 'It is well known that if the square root of a natural number is not an integer, then it is irrational. The decimal expansion of such square roots is infinite without any repeating pattern at all.
The square root of two is 1.41421356237309504880..., and the digital sum of the first one hundred decimal digits is 475.
For the first one hundred natural numbers, find the total of the digital sums of the first one hundred decimal digits for all the irrational square roots.
',
            ],
            [
                'title' => 'Almost equilateral triangles',
                'level' => 'medium',
                'answer' => 518408346,
                'score' => 20,
                'description' => 'It is easily proved that no equilateral triangle exists with integral length sides and integral area. However, the almost equilateral triangle 5-5-6 has an area of 12 square units.
We shall define an almost equilateral triangle to be a triangle for which two sides are equal and the third differs by no more than one unit.
Find the sum of the perimeters of all almost equilateral triangles with integral side lengths and area and whose perimeters do not exceed one billion (1,000,000,000).
',
            ],
            [
                'title' => 'Sum of squares of unitary divisors',
                'level' => 'medium',
                'answer' => 98792821,
                'score' => 25,
                'description' => 'A unitary divisor d of a number n is a divisor of n that has the property gcd(d, n/d) = 1.
The unitary divisors of 4! = 24 are 1, 3, 8 and 24.
The sum of their squares is 1^2 + 3^2 + 8^2 + 24^2 = 650.
Let S(n) represent the sum of the squares of the unitary divisors of n. Thus S(4!)=650.
Find S(100 000 000!) modulo 1 000 000 009.
',
            ],
            [
                'title' => 'Divisibility of factorials',
                'level' => 'medium',
                'answer' => 476001479068717,
                'score' => 25,
                'description' => 'The smallest number m such that 10 divides m! is m=5.
The smallest number m such that 25 divides m! is m=10.
Let s(n) be the smallest number m such that n divides m!.
So s(10)=5 and s(25)=10.
Let S(n) be ∑s(i) for 2 ≤ i ≤ n.
S(100)=2012.
Find S(108).
',
            ],
            [
                'title' => 'Divisor Square Sum',
                'level' => 'hard',
                'answer' => 1922364685,
                'score' => 30,
                'description' => 'For a positive integer n, let σ2(n) be the sum of the squares of its divisors. For example,
σ2(10) = 1 + 4 + 25 + 100 = 130.
Find the sum of all n, 0 < n < 64,000,000 such that σ2(n) is a perfect square.
',
            ],
            [
                'title' => 'Sphere Packing',
                'level' => 'hard',
                'answer' => 1590933,
                'score' => 30,
                'description' => 'What is the length of the shortest pipe, of internal radius 50mm, that can fully contain 21 balls of radii 30mm, 31mm, ..., 50mm?
Give your answer in micrometres (10-6 m) rounded to the nearest integer.
',
            ],
            [
                'title' => 'Prime Subset Sums',
                'level' => 'hard',
                'answer' => 9275262564250418,
                'score' => 30,
                'description' => 'Let S = {2, 3, 5, ..., 4999} be the set of prime numbers less than 5000.
Find the number of subsets of S, the sum of whose elements is a prime number.
Enter the rightmost 16 digits as your answer.',
            ],
            [
                'title' => 'Ant and seeds',
                'level' => 'hard',
                'answer' => 430.088247,
                'score' => 35,
                'description' => 'A laborious ant walks randomly on a 5x5 grid. The walk starts from the central square. At each step, the ant moves to an adjacent square at random, without leaving the grid; thus there are 2, 3 or 4 possible moves at each step depending on the ants position.
At the start of the walk, a seed is placed on each square of the lower row. When the ant is not carrying a seed and reaches a square of the lower row containing a seed, it will start to carry the seed. The ant will drop the seed on the first empty square of the upper row it eventually reaches.
What is the expected number of steps until all seeds have been dropped in the top row? 
Give your answer rounded to 6 decimal places.',
            ],
            [
                'title' => 'Steps in Euclids algorithm',
                'level' => 'hard',
                'answer' => 326624372659664,
                'score' => 30,
                'description' => 'Let E(x0, y0) be the number of steps it takes to determine the greatest common divisor of x0 and y0 with Euclid algorithm. More formally:
x1 = y0, y1 = x0 mod y0
xn = yn-1, yn = xn-1 mod yn-1
E(x0, y0) is the smallest n such that yn = 0.
We have E(1,1) = 1, E(10,6) = 3 and E(6,10) = 4.
Define S(N) as the sum of E(x,y) for 1 ≤ x,y ≤ N.
We have S(1) = 1, S(10) = 221 and S(100) = 39826.
Find S(5*10^6).
',
            ],[
                'title' => 'Modular Cubes',
                'level' => 'hard',
                'answer' => 4617456485273129588,
                'score' => 35,
                'description' => 'For a positive number n, define S(n) as the sum of the integers x, for which 1<x<n and
x3≡1 mod n.
When n=91, there are 8 possible values for x, namely : 9, 16, 22, 29, 53, 74, 79, 81.
Thus, S(91)=9+16+22+29+53+74+79+81=363.
Find S(13082761331670030)',        ]


        ];

        DB::table('problems')->insert($problems);
    }
}
